// syncAndSeed.js
const {
  sequelize,
  User,
  Role,
  MaterialMapping,
  SPCPlant,
  ProductionOrder,
  CodeMaster,
  MenuMaster,
  RoleMenuMapping,
  ConversionCharge,
  RMFreight,
  TransferPrice,
  ProductionRecording
 
} = require('./models');

async function syncAndSeed() {
  try {
    console.log('⚡ Dropping all tables...');
    await sequelize.drop(); // Clean drop of all tables
    console.log('✅ All tables dropped.');

    // --- Sync tables in correct order ---
    console.log('⚡ Creating tables in order...');
    await Role.sync({ force: true });
    console.log('✅ Role table ready.');
    await User.sync({ force: true });
    console.log('✅ User table ready.');
    await SPCPlant.sync({ force: true });
    console.log('✅ SPCPlant table ready.');
    await ProductionOrder.sync({ force: true });
    console.log('✅ ProductionOrder table ready.');
    await MaterialMapping.sync({ force: true });
    console.log('✅ MaterialMapping table ready.');
    await CodeMaster.sync({ force: true });
    console.log('✅ CodeMaster table ready.');
    await MenuMaster.sync({ force: true });
    console.log('✅ MenuMaster table ready.');
    await RoleMenuMapping.sync({ force: true });
    console.log('✅ RoleMenuMapping table ready.');
    const ApprovalWorkflow = require('./models/ApprovalWorkflow')(sequelize);
    await ApprovalWorkflow.sync({ force: true });
    console.log('✅ ApprovalWorkflow table ready.\n');
    const  DraftOrder = require('./models/DraftOrder')(sequelize);
    await DraftOrder.sync({ force: true });
    console.log('✅ DraftOrder table ready.\n');
    await ConversionCharge.sync({ force: true });
    console.log('✅ ConversionCharge table ready.\n');
    await RMFreight.sync({ force: true });
    console.log('✅ RMFreight table ready.\n');
    await TransferPrice.sync({ force: true });
    console.log('✅ TransferPrice table ready.\n');
    await ProductionRecording.sync({ force: true });
    console.log('✅ ProductionRecording table ready.\n');
   
    // --- Seed Roles ---
    const roleNames = ['admin', 'sales', 'spc_manager', 'spc_production'];
    for (const name of roleNames) {
      const exists = await Role.findOne({ where: { ROLE_ROLE_NAME: name } });
      if (!exists) await Role.create({ ROLE_ROLE_NAME: name });
    }

    // --- Seed Users ---
    const users = [
      { USER_ID: '808312', USER_USERNAME: 'Ayush Rastogi', USER_EMAIL: 'ayush.rastogi@tatasteel.com', roleName: 'admin' },
      { USER_ID: '163667', USER_USERNAME: 'Jyotsna Kumar', USER_EMAIL: 'jyotsna.kumar@tatasteel.com', roleName: 'spc_production' },
      { USER_ID: '7667778', USER_USERNAME: 'Arvind', USER_EMAIL: 'arvind@tatasteel.com', roleName: 'spc_manager' },
      { USER_ID: '995533', USER_USERNAME: 'Shyam', USER_EMAIL: 'shyam@tatasteel.com', roleName: 'sales' },
    ];
    for (const user of users) {
      const exists = await User.findOne({ where: { USER_ID: user.USER_ID } });
      if (!exists) {
        const role = await Role.findOne({ where: { ROLE_ROLE_NAME: user.roleName } });
        await User.create({
          USER_ID: user.USER_ID,
          USER_USERNAME: user.USER_USERNAME,
          USER_EMAIL: user.USER_EMAIL,
          USER_ROLE_ID: role.ROLE_ID
        });
      }
    }

    const freightData = [
      { FREIGHT_PLANT: 1439, FREIGHT_FIRST_LEG: 1412, FREIGHT_SECOND_LEG: 996 },
      { FREIGHT_PLANT: 1440, FREIGHT_FIRST_LEG: 647, FREIGHT_SECOND_LEG: 400 },
      { FREIGHT_PLANT: 2030, FREIGHT_FIRST_LEG: 2845, FREIGHT_SECOND_LEG: 280 },
      { FREIGHT_PLANT: 3546, FREIGHT_FIRST_LEG: 2327, FREIGHT_SECOND_LEG: 0 },
      { FREIGHT_PLANT: 3738, FREIGHT_FIRST_LEG: 2115, FREIGHT_SECOND_LEG: 0 },
      { FREIGHT_PLANT: 4134, FREIGHT_FIRST_LEG: 3021, FREIGHT_SECOND_LEG: 380 },
      { FREIGHT_PLANT: 4730, FREIGHT_FIRST_LEG: 3150, FREIGHT_SECOND_LEG: 300 },
      { FREIGHT_PLANT: 2123, FREIGHT_FIRST_LEG: 2845, FREIGHT_SECOND_LEG: 280 },
      { FREIGHT_PLANT: 3183, FREIGHT_FIRST_LEG: 2327, FREIGHT_SECOND_LEG: 300 },
      { FREIGHT_PLANT: 4340, FREIGHT_FIRST_LEG: 3021, FREIGHT_SECOND_LEG: 380 }
    ];

    for (const data of freightData) {
      const exists = await RMFreight.findOne({ 
        where: { FREIGHT_PLANT: data.FREIGHT_PLANT } 
      });
      if (!exists) await RMFreight.create(data);
    } 

    const conversionChargesData = [
  // SPC 1439 - MSWR
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 1439 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 1439 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1439, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 1440 - MSWR
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 1440 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 1440 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 1440, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 2030 - MSWR
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 2030 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 2030 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2030, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 3546 - MSWR
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8700 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },

      // SPC 3546 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8700 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },

      // SPC 3546 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8700 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3546, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },

      // SPC 3738 - MSWR
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },

      // SPC 3738 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },

      // SPC 3738 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 3738, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },

      // SPC 4134 - MSWR
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7500 },

      // SPC 4134 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7500 },

      // SPC 4134 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7900 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },
      { CONVERSION_CHARGE_SPC: 4134, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7500 },

      // SPC 4730 - MSWR
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7600 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7600 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6800 },

      // SPC 4730 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7600 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7600 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6800 },

      // SPC 4730 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8300 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7600 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7600 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7100 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6800 },
      { CONVERSION_CHARGE_SPC: 4730, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6800 },

      // SPC 2123 - MSWR
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 2123 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 2123 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 2123, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 3183 - MSWR
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 3183 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 3183 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 3183, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 4340 - MSWR
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'AIRCOOLED', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 4340 - TMT (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'TMT', CONVERSION_CHARGE_VALUE: 6975 },

      // SPC 4340 - DRAWN (same as Aircooled)
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '2-3mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 8175 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '3-4mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 7575 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '4-5mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '5-6mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '6-7mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '7-8mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '8-9mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '9-10mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '10-11mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 },
      { CONVERSION_CHARGE_SPC: 4340, CONVERSION_CHARGE_SECTION: '11-12mm', CONVERSION_CHARGE_WIRE_TYPE: 'DRAWN', CONVERSION_CHARGE_VALUE: 6975 }
    ];

    // --- Seed ConversionCharge ---
    for (const data of conversionChargesData) {
      const exists = await ConversionCharge.findOne({
        where: {
          CONVERSION_CHARGE_SPC: data.CONVERSION_CHARGE_SPC,
          CONVERSION_CHARGE_SECTION: data.CONVERSION_CHARGE_SECTION,
          CONVERSION_CHARGE_WIRE_TYPE: data.CONVERSION_CHARGE_WIRE_TYPE
        }
      });
      if (!exists) await ConversionCharge.create(data);
    }


    // --- Seed TransferPrice ---
    const transferPriceData = [
      // Apr-24
      { TRANSFER_PRICE_MONTH: 'Apr-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 43769 },
      { TRANSFER_PRICE_MONTH: 'Apr-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46269 },
      { TRANSFER_PRICE_MONTH: 'Apr-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 54710 },
      { TRANSFER_PRICE_MONTH: 'Apr-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 49824 },
      { TRANSFER_PRICE_MONTH: 'Apr-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 48063 },
      { TRANSFER_PRICE_MONTH: 'Apr-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 46736 },

      // May-24
      { TRANSFER_PRICE_MONTH: 'May-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 44185 },
      { TRANSFER_PRICE_MONTH: 'May-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46685 },
      { TRANSFER_PRICE_MONTH: 'May-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 68889 },
      { TRANSFER_PRICE_MONTH: 'May-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 52433 },
      { TRANSFER_PRICE_MONTH: 'May-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 50921 },
      { TRANSFER_PRICE_MONTH: 'May-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 50242 },

      // Jun-24
      { TRANSFER_PRICE_MONTH: 'Jun-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45640 },
      { TRANSFER_PRICE_MONTH: 'Jun-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48140 },
      { TRANSFER_PRICE_MONTH: 'Jun-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 60452 },
      { TRANSFER_PRICE_MONTH: 'Jun-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 54638 },
      { TRANSFER_PRICE_MONTH: 'Jun-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 52676 },
      { TRANSFER_PRICE_MONTH: 'Jun-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 51653 },

      // Jul-24
      { TRANSFER_PRICE_MONTH: 'Jul-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 46113 },
      { TRANSFER_PRICE_MONTH: 'Jul-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48613 },
      { TRANSFER_PRICE_MONTH: 'Jul-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 59011 },
      { TRANSFER_PRICE_MONTH: 'Jul-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 53086 },
      { TRANSFER_PRICE_MONTH: 'Jul-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 52058 },
      { TRANSFER_PRICE_MONTH: 'Jul-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 50546 },

      // Aug-24
      { TRANSFER_PRICE_MONTH: 'Aug-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 46110 },
      { TRANSFER_PRICE_MONTH: 'Aug-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48610 },
      { TRANSFER_PRICE_MONTH: 'Aug-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 54714 },
      { TRANSFER_PRICE_MONTH: 'Aug-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 48165 },
      { TRANSFER_PRICE_MONTH: 'Aug-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 48345 },
      { TRANSFER_PRICE_MONTH: 'Aug-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 47900 },

      // Sep-24
      { TRANSFER_PRICE_MONTH: 'Sep-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45956 },
      { TRANSFER_PRICE_MONTH: 'Sep-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48456 },
      { TRANSFER_PRICE_MONTH: 'Sep-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 52207 },
      { TRANSFER_PRICE_MONTH: 'Sep-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 47219 },
      { TRANSFER_PRICE_MONTH: 'Sep-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45551 },
      { TRANSFER_PRICE_MONTH: 'Sep-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 44363 },

      // Oct-24
      { TRANSFER_PRICE_MONTH: 'Oct-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45379 },
      { TRANSFER_PRICE_MONTH: 'Oct-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 47879 },
      { TRANSFER_PRICE_MONTH: 'Oct-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 55337 },
      { TRANSFER_PRICE_MONTH: 'Oct-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 47360 },
      { TRANSFER_PRICE_MONTH: 'Oct-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45551 },
      { TRANSFER_PRICE_MONTH: 'Oct-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 44363 },

      // Nov-24
      { TRANSFER_PRICE_MONTH: 'Nov-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45551 },
      { TRANSFER_PRICE_MONTH: 'Nov-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48051 },
      { TRANSFER_PRICE_MONTH: 'Nov-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 56953 },
      { TRANSFER_PRICE_MONTH: 'Nov-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 50442 },
      { TRANSFER_PRICE_MONTH: 'Nov-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 49949 },
      { TRANSFER_PRICE_MONTH: 'Nov-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 47872 },

      // Dec-24
      { TRANSFER_PRICE_MONTH: 'Dec-24', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45872 },
      { TRANSFER_PRICE_MONTH: 'Dec-24', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48372 },
      { TRANSFER_PRICE_MONTH: 'Dec-24', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 55572 },
      { TRANSFER_PRICE_MONTH: 'Dec-24', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 50481 },
      { TRANSFER_PRICE_MONTH: 'Dec-24', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 49372 },
      { TRANSFER_PRICE_MONTH: 'Dec-24', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 47629 },

      // Jan-25
      { TRANSFER_PRICE_MONTH: 'Jan-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45995 },
      { TRANSFER_PRICE_MONTH: 'Jan-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48495 },
      { TRANSFER_PRICE_MONTH: 'Jan-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 0 },
      { TRANSFER_PRICE_MONTH: 'Jan-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 49369 },
      { TRANSFER_PRICE_MONTH: 'Jan-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 48141 },
      { TRANSFER_PRICE_MONTH: 'Jan-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 45433 },

      // Feb-25
      { TRANSFER_PRICE_MONTH: 'Feb-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45952 },
      { TRANSFER_PRICE_MONTH: 'Feb-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48452 },
      { TRANSFER_PRICE_MONTH: 'Feb-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 55127 },
      { TRANSFER_PRICE_MONTH: 'Feb-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 47585 },
      { TRANSFER_PRICE_MONTH: 'Feb-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 47103 },
      { TRANSFER_PRICE_MONTH: 'Feb-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 45718 },

      // Mar-25
      { TRANSFER_PRICE_MONTH: 'Mar-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 46363 },
      { TRANSFER_PRICE_MONTH: 'Mar-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48863 },
      { TRANSFER_PRICE_MONTH: 'Mar-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 53479 },
      { TRANSFER_PRICE_MONTH: 'Mar-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 48398 },
      { TRANSFER_PRICE_MONTH: 'Mar-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 46739 },
      { TRANSFER_PRICE_MONTH: 'Mar-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 45293 },

      // Apr-25
      { TRANSFER_PRICE_MONTH: 'Apr-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 46797 },
      { TRANSFER_PRICE_MONTH: 'Apr-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48327 },
      { TRANSFER_PRICE_MONTH: 'Apr-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 58112 },
      { TRANSFER_PRICE_MONTH: 'Apr-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 51832 },
      { TRANSFER_PRICE_MONTH: 'Apr-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 50257 },
      { TRANSFER_PRICE_MONTH: 'Apr-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 48757 },

      // May-25
      { TRANSFER_PRICE_MONTH: 'May-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 47176 },
      { TRANSFER_PRICE_MONTH: 'May-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48706 },
      { TRANSFER_PRICE_MONTH: 'May-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 59721 },
      { TRANSFER_PRICE_MONTH: 'May-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 55172 },
      { TRANSFER_PRICE_MONTH: 'May-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 52524 },
      { TRANSFER_PRICE_MONTH: 'May-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 51405 },

      // Jun-25
      { TRANSFER_PRICE_MONTH: 'Jun-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 47053 },
      { TRANSFER_PRICE_MONTH: 'Jun-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48583 },
      { TRANSFER_PRICE_MONTH: 'Jun-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 53775 },
      { TRANSFER_PRICE_MONTH: 'Jun-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 53096 },
      { TRANSFER_PRICE_MONTH: 'Jun-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 51868 },
      { TRANSFER_PRICE_MONTH: 'Jun-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 50253 },

      // Jul-25
      { TRANSFER_PRICE_MONTH: 'Jul-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 46703 },
      { TRANSFER_PRICE_MONTH: 'Jul-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 48233 },
      { TRANSFER_PRICE_MONTH: 'Jul-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 55782 },
      { TRANSFER_PRICE_MONTH: 'Jul-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 50002 },
      { TRANSFER_PRICE_MONTH: 'Jul-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 48143 },
      { TRANSFER_PRICE_MONTH: 'Jul-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 46869 },

      // Aug-25
      { TRANSFER_PRICE_MONTH: 'Aug-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45726 },
      { TRANSFER_PRICE_MONTH: 'Aug-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 47256 },
      { TRANSFER_PRICE_MONTH: 'Aug-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Aug-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Aug-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Aug-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      // Sep-25
      { TRANSFER_PRICE_MONTH: 'Sep-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Sep-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Sep-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Sep-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Sep-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Sep-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      // Oct-25 to Mar-26 (same as Sep-25 values)
      { TRANSFER_PRICE_MONTH: 'Oct-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Oct-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Oct-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Oct-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Oct-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Oct-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      { TRANSFER_PRICE_MONTH: 'Nov-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Nov-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Nov-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Nov-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Nov-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Nov-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      { TRANSFER_PRICE_MONTH: 'Dec-25', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Dec-25', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Dec-25', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Dec-25', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Dec-25', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Dec-25', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      { TRANSFER_PRICE_MONTH: 'Jan-26', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Jan-26', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Jan-26', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Jan-26', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Jan-26', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Jan-26', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      { TRANSFER_PRICE_MONTH: 'Feb-26', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Feb-26', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Feb-26', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Feb-26', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Feb-26', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Feb-26', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 },

      { TRANSFER_PRICE_MONTH: 'Mar-26', TRANSFER_PRICE_RM_TYPE: 'WIRE_ROD', TRANSFER_PRICE_VALUE: 45280 },
      { TRANSFER_PRICE_MONTH: 'Mar-26', TRANSFER_PRICE_RM_TYPE: 'AIRCOOLED', TRANSFER_PRICE_VALUE: 46810 },
      { TRANSFER_PRICE_MONTH: 'Mar-26', TRANSFER_PRICE_RM_TYPE: 'TMT_6MM', TRANSFER_PRICE_VALUE: 51444 },
      { TRANSFER_PRICE_MONTH: 'Mar-26', TRANSFER_PRICE_RM_TYPE: 'TMT_8MM', TRANSFER_PRICE_VALUE: 46275 },
      { TRANSFER_PRICE_MONTH: 'Mar-26', TRANSFER_PRICE_RM_TYPE: 'TMT_10MM', TRANSFER_PRICE_VALUE: 45064 },
      { TRANSFER_PRICE_MONTH: 'Mar-26', TRANSFER_PRICE_RM_TYPE: 'TMT_12MM', TRANSFER_PRICE_VALUE: 43216 }
    ];

    for (const data of transferPriceData) {
      const exists = await TransferPrice.findOne({
        where: {
          TRANSFER_PRICE_MONTH: data.TRANSFER_PRICE_MONTH,
          TRANSFER_PRICE_RM_TYPE: data.TRANSFER_PRICE_RM_TYPE
        }
      });
      if (!exists) await TransferPrice.create(data);
    }

    // --- Seed SPCPlants ---
    const spcPlantsList = [
      { SPC_PLANTS_ID: '1439', SPC_PLANTS_NAME: 'Sagar Business' },
      { SPC_PLANTS_ID: '1440', SPC_PLANTS_NAME: 'SK Weldmesh' },
      { SPC_PLANTS_ID: '2030', SPC_PLANTS_NAME: 'TR Weldmesh' },
      { SPC_PLANTS_ID: '3546', SPC_PLANTS_NAME: 'Sachi Steel' },
      { SPC_PLANTS_ID: '3738', SPC_PLANTS_NAME: 'Systematic' },
      { SPC_PLANTS_ID: '4134', SPC_PLANTS_NAME: 'SSR Enterprises' },
      { SPC_PLANTS_ID: '4730', SPC_PLANTS_NAME: 'Tulsyan' },
      { SPC_PLANTS_ID: '4340', SPC_PLANTS_NAME: 'Samrat' },
      { SPC_PLANTS_ID: '2123', SPC_PLANTS_NAME: 'Daga' },
      { SPC_PLANTS_ID: '3183', SPC_PLANTS_NAME: 'Indu' },
    ];
    for (const plant of spcPlantsList) {
      const exists = await SPCPlant.findByPk(plant.SPC_PLANTS_ID);
      if (!exists) await SPCPlant.create(plant);
    }

      //  --- Seed MaterialMapping ---
     const materialList = [
      { matnr: '365901', description: 'TISCON-TMT COIL IS1786 Fe500D MA 6.00', alias: 'AC 500D - 6mm' },
      { matnr: '507245', description: 'WIRE RODS IS 7887: Grade 4 7.00mm', alias: 'Gr.4 - 7mm' },
      { matnr: '507248', description: 'WIRE RODS IS 7887: Grade 5 6.00mm', alias: 'Gr.5 - 6mm' },
      { matnr: '507251', description: 'WIRE RODS IS 7887: Grade 6 5.50mm', alias: 'Gr.6 - 5.5mm' },
      { matnr: '507263', description: 'WIRE RODS IS 7887: Grade 6 7.00mm', alias: 'Gr.6 - 7mm' },
      { matnr: '507264', description: 'WIRE RODS IS 7887: Grade 6 8.00mm', alias: 'Gr.6 - 8mm' },
      { matnr: '507265', description: 'WIRE RODS IS 7887: Grade 3 5.50mm', alias: 'Gr.3 - 5.5mm' },
      { matnr: '1221979', description: 'WIRE RODS IS 7887: Grade 6 9.00mm', alias: 'Gr.6 - 9mm' },
      { matnr: '1266358', description: 'WIRE RODS IS:7887 Grade 7 9.00mm', alias: 'Gr.7 - 9mm' },
      { matnr: '1266360', description: 'WIRE RODS IS:7887 Grade 7 11.00mm', alias: 'Gr.7 - 11mm' },
      { matnr: '1266361', description: 'WIRE RODS IS:7887 Grade 7 12.00mm', alias: 'Gr.7 - 12mm' },
      { matnr: '3214183', description: 'WIRE RODS IS:7887 Grade 7M 10.00mm', alias: 'Gr.7M - 10mm' },
      { matnr: '3567186', description: 'TISCON-TMT Fe500D Air Cool 9.00mm', alias: 'AC 500D - 9mm' },
      { matnr: '3570532', description: 'TISCON-TMT Fe500D Air Cool 7.00mm', alias: 'AC 500D - 7mm' },
      { matnr: '3481751', description: 'WIRE RODS IS:7887 Grade 7M 9.00mm', alias: 'Gr.7M - 9mm' },
      { matnr: '507252', description: 'WIRE RODS IS 7887: Grade 6 6.00mm', alias: 'Gr.6 - 6mm' },
      { matnr: '521556', description: 'WIRE RODS IS 7887: Grade 7 7.00mm', alias: 'Gr.7 - 7mm' },
      { matnr: '507239', description: 'WIRE RODS IS:7887 Grade 2 5.50mm', alias: 'Gr.2 - 5.5mm' },
      { matnr: '3763864', description: 'WIRE RODS IS:7887 Grade 7M 11.00mm', alias: 'Gr.7M - 11mm' },
      { matnr: '1266359', description: 'WIRE RODS IS:7887 Grade 7 10.00mm', alias: 'Gr.7 - 10mm' },
      { matnr: '521557', description: 'WIRE RODS IS 7887: Grade 7 8.00mm', alias: 'Gr.7 - 8mm' },
      { matnr: '1270992', description: 'WIRE RODS IS:7887 Grade 7 13.00mm', alias: 'Gr.7 - 13mm' },
      { matnr: '521555', description: 'WIRE RODS IS 7887: Grade 7 6.00mm', alias: 'Gr.7 - 6mm' },
      { matnr: '3767018', description: 'WIRE RODS IS:7887 Grade 7M 12.00mm', alias: 'Gr.7M - 12mm' },
      { matnr: '507249', description: 'WIRE RODS IS 7887: Grade 5 7.00mm', alias: 'Gr.5 - 7mm' },
      { matnr: '507234', description: 'WIRE RODS IS 7887: Grade 1 5.50mm', alias: 'Gr.1 - 5.5mm' },
      { matnr: '3570533', description: 'TISCON-TMT Fe500D Air Cool 11.00mm', alias: 'AC 500D - 11mm' },
      { matnr: '355635', description: 'TISCON - COIL IS1786 Fe500D MA 8.00', alias: 'AC 500D - 8mm' },
      { matnr: '356333', description: 'TISCON TMT COIL IS:1786 FE500D MA 12MM', alias: 'AC 500D - 12mm' },
      { matnr: '357605', description: 'TISCON TMT COIL IS:1786 FE500D MA 10MM', alias: 'AC 500D - 10mm' },
      { matnr: '1114347', description: 'WIRE RODS IS7887: Grade 3 [Gen] 5.50mm', alias: 'Gr.3 - 5.5mm' },
      { matnr: '3906581', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 6.00mm', alias: 'Gr.5 [CRS] - 6mm' },
      { matnr: '3906582', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 7.00mm', alias: 'Gr.5 [CRS] - 7mm' },
      { matnr: '3906583', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 8.00mm', alias: 'Gr.5 [CRS] - 8mm' },
      { matnr: '3906409', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 8.50mm', alias: 'Gr.5 [CRS] - 8.5mm' },
      { matnr: '3906584', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 9.00mm', alias: 'Gr.5 [CRS] - 9mm' },
      { matnr: '3906585', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 10.00mm', alias: 'Gr.5 [CRS] - 10mm' },
      { matnr: '3906410', description: 'WIRE RODS IS 7887 Grade 5 [CRS] 11.00mm', alias: 'Gr.5 [CRS] - 11mm' },
      { matnr: '521554', description: 'WIRE RODS IS 7887: Grade 7 5.50mm', alias: 'Gr.7 - 5.5mm' },
      { matnr: '4014775', description: 'TISCON TMT COIL IS 1786 Fe550D [AC] 7.00mm', alias: 'AC 550D - 7mm' },
      { matnr: '4014776', description: 'TISCON TMT COIL IS 1786 Fe550D [AC] 8.00mm', alias: 'AC 550D - 8mm' },
      { matnr: '4014777', description: 'TISCON TMT COIL IS 1786 Fe550D [AC] 9.00mm', alias: 'AC 550D - 9mm' },
      { matnr: '4014778', description: 'TISCON TMT COIL IS 1786 Fe550D [AC] 10.00mm', alias: 'AC 550D - 10mm' },
      { matnr: '4014779', description: 'TISCON TMT COIL IS 1786 Fe550D [AC] 11.00mm', alias: 'AC 550D - 11mm' },
      { matnr: '4014780', description: 'TISCON TMT COIL IS 1786 Fe550D [AC] 12.00mm', alias: 'AC 550D - 12mm' },
      { matnr: '3848341', description: 'TISCON TMT COIL IS1786 Fe550D [CRSAC] 6.00mm', alias: 'AC-CRS 550D - 6mm' },
      { matnr: '3848342', description: 'TISCON TMT COIL IS1786 Fe550D [CRSAC] 7.00mm', alias: 'AC-CRS 550D - 7mm' },
      { matnr: '3848220', description: 'TISCON TMT COIL IS1786 Fe550D [CRSAC] 8.00mm', alias: 'AC-CRS 550D - 8mm' },
      { matnr: '3848343', description: 'TISCON TMT COIL IS1786 Fe550D [CRSAC] 9.00mm', alias: 'AC-CRS 550D - 9mm' },
      { matnr: '3848344', description: 'TISCON TMT COIL IS1786 Fe550D [CRSAC] 10.00mm', alias: 'AC-CRS 550D - 10mm' },
      { matnr: '1303581', description: 'TISCON-TMT IS 1786 Fe 550D 12.00mm Coil', alias: '550D - 12mm' },
      { matnr: '321668', description: 'TISCON-TMT COIL IS:1786 FE500 D 8mm', alias: '500D - 8mm' },
      { matnr: '322499', description: 'TISCON TMT COIL IS:1786 FE500 D 6mm', alias: '500D - 6mm' },
      { matnr: '322501', description: 'TISCON-TMT COIL IS:1786 FE500 D 10mm', alias: '500D - 10mm' },
      { matnr: '1323332', description: 'TISCON-TMT IS 1786 Fe 550D 8.00mm Coil', alias: '550D - 8mm' },
      { matnr: '1323413', description: 'TISCON-TMT IS 1786 Fe 550D 10.00mm Coil', alias: '550D - 10mm' },
      { matnr: '1323414', description: 'TISCON-TMT IS 1786 Fe 550D 12.00mm Coil', alias: '550D - 12mm' },
      { matnr: '322503', description: 'TISCON TMT COIL IS:1786 FE500 D 12mm', alias: '500D - 12mm' }
  ];
    for (const mat of materialList) {
      const exists = await MaterialMapping.findByPk(mat.matnr);
      if (!exists) {
        await MaterialMapping.create({
          MATERIAL_MAPPING_ID: mat.matnr,
          MATERIAL_MAPPING_DESCRIPTION: mat.description,
          MATERIAL_MAPPING_ALIAS: mat.alias,
          MATERIAL_MAPPING_TYPE: 'FG',
        });
      }
    }

    // --- Seed MenuMaster based on frontend routes ---
    const menuEntries = [
      { MENU_MASTER_NAME: 'Production Order', MENU_MASTER_PATH: '/ProductionOrderForm' },
      { MENU_MASTER_NAME: 'Approval Dashboard', MENU_MASTER_PATH: '/ApprovalDashboard' },
      { MENU_MASTER_NAME: 'Production Recording', MENU_MASTER_PATH: '/ProductionRecording' },
      { MENU_MASTER_NAME: 'Tag Print', MENU_MASTER_PATH: '/TagPrint' },
      { MENU_MASTER_NAME: 'Smart Invoicing', MENU_MASTER_PATH: '/SmartInvoicing' },
      { MENU_MASTER_NAME: 'Notifications', MENU_MASTER_PATH: '/notifications' },
    ];

    for (const menu of menuEntries) {
      const exists = await MenuMaster.findOne({ where: { MENU_MASTER_NAME: menu.MENU_MASTER_NAME } });
      if (!exists) await MenuMaster.create(menu);
    }
    
    // --- Seed RoleMenuMapping ---
    const roleMenuMappings = [
      { roleName: 'sales', menuName: 'Production Order', PERMISSIONS: 'READ_WRITE' },
      { roleName: 'admin', menuName: 'Production Order', PERMISSIONS: 'READ_WRITE' },

      { roleName: 'sales', menuName: 'Approval Dashboard', PERMISSIONS: 'READ' },
      { roleName: 'spc_manager', menuName: 'Approval Dashboard', PERMISSIONS: 'READ' },
      { roleName: 'spc_production', menuName: 'Approval Dashboard', PERMISSIONS: 'READ' },
      { roleName: 'admin', menuName: 'Approval Dashboard', PERMISSIONS: 'READ_WRITE' },

      { roleName: 'spc_production', menuName: 'Production Recording', PERMISSIONS: 'READ_WRITE' },
      { roleName: 'admin', menuName: 'Production Recording', PERMISSIONS: 'READ_WRITE' },

      { roleName: 'spc_production', menuName: 'Tag Print', PERMISSIONS: 'READ_WRITE' },
      { roleName: 'admin', menuName: 'Tag Print', PERMISSIONS: 'READ_WRITE' },

      { roleName: 'admin', menuName: 'Smart Invoicing', PERMISSIONS: 'READ_WRITE' },

      { roleName: 'sales', menuName: 'Notifications', PERMISSIONS: 'READ' },
      { roleName: 'spc_manager', menuName: 'Notifications', PERMISSIONS: 'READ' },
      { roleName: 'spc_production', menuName: 'Notifications', PERMISSIONS: 'READ' },
      { roleName: 'admin', menuName: 'Notifications', PERMISSIONS: 'READ_WRITE_DELETE' },
    ];

    const roles = await Role.findAll();
    const menus = await MenuMaster.findAll();
    for (const mapping of roleMenuMappings) {
      const role = roles.find(r => r.ROLE_ROLE_NAME === mapping.roleName);
      const menu = menus.find(m => m.MENU_MASTER_NAME === mapping.menuName);
      if (!role || !menu) continue;
      const exists = await RoleMenuMapping.findOne({ 
      where: { 
        ROLE_MENU_MAPPING_ROLE_ID: role.ROLE_ID,
        ROLE_MENU_MAPPING_MENU_ID: menu.MENU_MASTER_ID
      } 
    });

      if (!exists) {
        await RoleMenuMapping.create({
          ROLE_MENU_MAPPING_ROLE_ID: role.ROLE_ID,
          ROLE_MENU_MAPPING_MENU_ID: menu.MENU_MASTER_ID,
          ROLE_MENU_MAPPING_CAN_VIEW: mapping.PERMISSIONS.includes('READ'),
          ROLE_MENU_MAPPING_CAN_CREATE: mapping.PERMISSIONS.includes('WRITE'),
          ROLE_MENU_MAPPING_CAN_EDIT: mapping.PERMISSIONS.includes('WRITE'),
          ROLE_MENU_MAPPING_CAN_DELETE: mapping.PERMISSIONS.includes('DELETE'),
        });
      }
    }

    
const orderStatusEntries = [
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "PENDING",
    CODE_MASTER_VALUE: "Pending",
    CODE_MASTER_DESCRIPTION: "Order awaiting any workflow action",
    CODE_MASTER_ORDER: 1
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "APPROVED",
    CODE_MASTER_VALUE: "Approved",
    CODE_MASTER_DESCRIPTION: "Order fully approved at all workflow levels",
    CODE_MASTER_ORDER: 2
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "REJECTED",
    CODE_MASTER_VALUE: "Rejected",
    CODE_MASTER_DESCRIPTION: "Order rejected at any workflow level",
    CODE_MASTER_ORDER: 3
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "PENDING_LEVEL_1",
    CODE_MASTER_VALUE: "Pending with SPC Manager",
    CODE_MASTER_DESCRIPTION: "Approval required from SPC Manager (Level 1)",
    CODE_MASTER_ORDER: 4
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "PENDING_LEVEL_2",
    CODE_MASTER_VALUE: "Pending with SPC Production",
    CODE_MASTER_DESCRIPTION: "Approval required from SPC Production (Level 2)",
    CODE_MASTER_ORDER: 5
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "APPROVED_LEVEL_1",
    CODE_MASTER_VALUE: "Approved by SPC Manager",
    CODE_MASTER_DESCRIPTION: "Order approved by SPC Manager (Level 1)",
    CODE_MASTER_ORDER: 6
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "APPROVED_LEVEL_2",
    CODE_MASTER_VALUE: "Approved by SPC Production",
    CODE_MASTER_DESCRIPTION: "Order approved by SPC Production (Level 2)",
    CODE_MASTER_ORDER: 7
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "REJECTED_LEVEL_1",
    CODE_MASTER_VALUE: "Rejected by SPC Manager",
    CODE_MASTER_DESCRIPTION: "Order rejected by SPC Manager (Level 1)",
    CODE_MASTER_ORDER: 8
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "REJECTED_LEVEL_2",
    CODE_MASTER_VALUE: "Rejected by SPC Production",
    CODE_MASTER_DESCRIPTION: "Order rejected by SPC Production (Level 2)",
    CODE_MASTER_ORDER: 9
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "DELETED",
    CODE_MASTER_VALUE: "Deleted by Admin",
    CODE_MASTER_DESCRIPTION: "Order deleted by admin",
    CODE_MASTER_ORDER: 10
  },
  // 🔹 Return Statuses
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "RETURN",
    CODE_MASTER_VALUE: "Returned",
    CODE_MASTER_DESCRIPTION: "Order returned to previous level",
    CODE_MASTER_ORDER: 11
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "RETURN_LEVEL_1",
    CODE_MASTER_VALUE: "Returned to SPC Manager",
    CODE_MASTER_DESCRIPTION: "Order returned from SPC Production to SPC Manager",
    CODE_MASTER_ORDER: 12
  },
  {
    CODE_MASTER_CATEGORY: "ORDER_STATUS",
    CODE_MASTER_KEY: "RETURN_TO_SALES",
    CODE_MASTER_VALUE: "Returned to Sales",
    CODE_MASTER_DESCRIPTION: "Order returned from SPC Manager or SPC Production to Sales",
    CODE_MASTER_ORDER: 13
  }
];

    async function seedOrderStatusCodes() {
    for (const entry of orderStatusEntries) {
      const exists = await CodeMaster.findOne({
        where: {
          CODE_MASTER_CATEGORY: entry.CODE_MASTER_CATEGORY,
          CODE_MASTER_KEY: entry.CODE_MASTER_KEY,
        },
      });
      if (!exists) {
        await CodeMaster.create(entry, { userId: "SYSTEM" });
        console.log(`Inserted ORDER_STATUS: ${entry.CODE_MASTER_KEY}`);
      } else {
        console.log(`Already exists: ${entry.CODE_MASTER_KEY}`);
      }
    }
    console.log("✅ ORDER_STATUS codes seeded");
    }

    await seedOrderStatusCodes();

    console.log('\n🎉 All tables synced and seeded successfully.');
    process.exit(0);

  } catch (err) {
    console.error('❌ Error during sync/seed:', err);
    process.exit(1);
  }
}

syncAndSeed();